# These are supported funding model platforms

github: [TheWebTech]
open_collective: # Replace with a single Open Collective username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: 
