# These are supported funding model platforms

github: [TheWebTech]
open_collective: # Replace with a single Open Collective username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=ML3VP8M5XGZP2&currency_code=USD&source=url
